name: Build SoftEther ARM64 musl

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: arm64

      - name: Test ARM64
        run: |
          docker run --rm --platform linux/arm64 alpine:3.19 uname -m

      - name: Build SoftEther
        run: |
          mkdir -p output

          docker run --rm \
            --platform linux/arm64 \
            -v "$PWD/output:/output" \
            alpine:3.19 \
            sh -euxc '
              apk add --no-cache \
                build-base \
                binutils \
                linux-headers \
                readline-dev \
                openssl-dev \
                ncurses-dev \
                git \
                cmake \
                zlib-dev \
                libsodium-dev \
                gnu-libiconv \
                libiconv \
                file

              cd /tmp

              git clone --depth 1 \
                https://github.com/SoftEtherVPN/SoftEtherVPN.git

              cd SoftEtherVPN

              git submodule update --init --depth 1

              export USE_MUSL=YES

              ./configure

              make -C build -j2

              echo
              echo "===== VPN SERVER ====="
              file build/vpnserver
              ldd build/vpnserver || true

              echo
              echo "===== VPN CMD ====="
              file build/vpncmd
              ldd build/vpncmd || true

              echo
              echo "===== COPY ====="

              cp build/vpnserver /output/
              cp build/vpncmd /output/
              cp build/hamcore.se2 /output/

              chmod 755 /output/vpnserver
              chmod 755 /output/vpncmd
            '

      - name: Verify
        run: |
          echo "===== ARTIFACTS ====="
          ls -lh output/

          echo
          echo "===== vpnserver ====="
          file output/vpnserver

          echo
          echo "===== vpncmd ====="
          file output/vpncmd

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: softether-arm64-musl
          path: output/
